# Generated by Django 5.0 on 2023-12-22 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_category_options_remove_category_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blogs.post'),
        ),
    ]
